function users(root, args, context) {
    return context.prisma.users()
}

function projects(root, args, context) {
    return context.prisma.projects()
}


// At its core this is referencing type Query in the autogenerated PrismaSchema
// projects(where: ProjectWhereInput, orderBy: ProjectOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [Project]!
// $where argument expects ProjectWhereInput type also declared in PrismaSchema
// ProjectWhereInput has a parameter 
// avi_roles_on_project: Avi_RolesWhereInput
// this destructuring will allow argument structure of:
// {
//     "rolesOfInterest": {
//       "avi_gaffer": false
//     }
//   } 
// args returns data in the format { where: {"avi_gaffer": true} }
// hence, args.where gets me the properties of interest
// then I submit the query as per the spec -- projects(where:ProjectWhereInput)
async function filterProjectsByRole(parent, args, context, info){
    const ProjectWhereInput = args ? {
        "avi_roles_on_project": {...args.where}
    } : {} 
    
    const filteredProjects = await context.prisma.projects({"where": ProjectWhereInput})
    return filteredProjects    
}



module.exports = {
    users,
    projects,
    filterProjectsByRole
}